version: '3.8'
Services: 
N8n:
Image: n8nio/n8n:latest
Container_name: n8n_security_monitor
Restart: always
Ports:
- <<5678:5678>>
Environement:
-N8N_BASIC_AUTH_ACTIVE=true
-N8N_BASIC_AUTH_USER=admin
-N8N_BASIC_AUTH_PASSWORD=changeme
Volumes:
-N8n_data:/home/node/.n8n
Networks:
-Security-net

Networks:
-security_net:
 Driver:bridge

Volumes:
N8n_data:
